# Generated by Django 5.0.8 on 2026-10-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_position_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
